/* Marleo i18n voor subpagina's (NL/EN/FR). Taal: ?lang= → localStorage → browser. */
(function(){
var L=['nl','en','fr'];
function pick(){var q=(location.search.match(/[?&]lang=(nl|en|fr)/)||[])[1];if(q){try{localStorage.setItem('mlang',q)}catch(e){}return q}
 try{var s=localStorage.getItem('mlang');if(L.indexOf(s)>=0)return s}catch(e){}
 var n=(navigator.language||'nl').slice(0,2);return L.indexOf(n)>=0?n:'nl'}
var lang=pick();window.MLANG=lang;document.documentElement.lang=lang;
var D={
/* gedeeld */
"Laatst bijgewerkt: 30 september 2026":["Last updated: 30 September 2026","Dernière mise à jour : 30 septembre 2026"],
"← Terug naar marleo.tech":["← Back to marleo.tech","← Retour à marleo.tech"],
"Privacy":["Privacy","Confidentialité"],"Algemene voorwaarden":["Terms and conditions","Conditions générales"],"NIS2 & AI Act":["NIS2 & AI Act","NIS2 & AI Act"],
"E-mail:":["Email:","E-mail :"],"· Tel:":["· Phone:","· Tél. :"],"Graaf van Hoornestraat 2B, 9850 Nevele, België":["Graaf van Hoornestraat 2B, 9850 Nevele, Belgium","Graaf van Hoornestraat 2B, 9850 Nevele, Belgique"],
"BTW BE 0751.641.419":["VAT BE 0751.641.419","TVA BE 0751.641.419"],
/* afspraak */
"Plan een":["Book a","Prenez"],"afspraak":["meeting","rendez-vous"],
"Kies zelf een moment dat past. Vrijblijvend en zonder verplichting.":["Pick a time that suits you. Free and without obligation.","Choisissez le moment qui vous convient. Gratuit et sans engagement."],
"Kon de beschikbaarheid niet laden. Probeer later opnieuw of mail naar info@marleo.tech.":["Could not load availability. Please try again later or email info@marleo.tech.","Impossible de charger les disponibilités. Réessayez plus tard ou écrivez à info@marleo.tech."],
"Beschikbare momenten laden…":["Loading availability…","Chargement des disponibilités…"],
"1 · Soort afspraak":["1 · Type of meeting","1 · Type de rendez-vous"],"2 · Kies een dag":["2 · Choose a day","2 · Choisissez un jour"],"3 · Kies een uur":["3 · Choose a time","3 · Choisissez une heure"],"4 · Jouw gegevens":["4 · Your details","4 · Vos coordonnées"],
"Naam *":["Name *","Nom *"],"Bedrijf":["Company","Entreprise"],"E-mail *":["Email *","E-mail *"],"Telefoon":["Phone","Téléphone"],"Waarover gaat het? (optioneel)":["What is it about? (optional)","De quoi s'agit-il ? (facultatif)"],
"Afspraak aanvragen":["Request meeting","Demander un rendez-vous"],"Afspraak bevestigen":["Confirm meeting","Confirmer le rendez-vous"],
"Er zijn momenteel geen momenten beschikbaar.":["There are currently no available slots.","Aucun créneau n'est disponible pour le moment."],
"Stuur gerust een mail naar":["Feel free to email","N'hésitez pas à écrire à"],"of bel +32 456 92 00 25.":["or call +32 456 92 00 25.","ou appelez le +32 456 92 00 25."],
"Marleo · Nevele, België ·":["Marleo · Nevele, Belgium ·","Marleo · Nevele, Belgique ·"],
"bv. nieuwe website, webshop, IT-hulp…":["e.g. new website, webshop, IT help…","ex. nouveau site, boutique en ligne, aide IT…"],
"Afspraak maken · Marleo":["Book a meeting · Marleo","Prendre rendez-vous · Marleo"],
"Videogesprek":["Video call","Appel vidéo"],"Via Google Meet, link krijg je per mail":["Via Google Meet, you get the link by email","Via Google Meet, lien envoyé par e-mail"],
"Telefonisch":["By phone","Par téléphone"],"Ik bel jou op":["I will call you","Je vous appelle"],"Bij jou langs":["At your place","Chez vous"],"In de regio Nevele / Gent / Deinze":["In the Nevele / Ghent / Deinze area","Dans la région de Nevele / Gand / Deinze"],
"Bezig…":["Sending…","Envoi…"],"Er ging iets mis":["Something went wrong","Une erreur s'est produite"],"Geen verbinding, probeer opnieuw":["No connection, please try again","Pas de connexion, réessayez"],
"om":["at","à"],"Afspraak bevestigd":["Meeting confirmed","Rendez-vous confirmé"],"Aanvraag ontvangen":["Request received","Demande reçue"],
"Je krijgt een bevestiging per mail":["You will receive a confirmation by email","Vous recevrez une confirmation par e-mail"],"met de Google Meet-link.":["with the Google Meet link.","avec le lien Google Meet."],
"Ik bevestig je afspraak zo snel mogelijk per mail. Dit tijdstip is intussen voor jou gereserveerd.":["I will confirm your meeting by email as soon as possible. This time slot is reserved for you in the meantime.","Je confirme votre rendez-vous par e-mail au plus vite. Ce créneau vous est réservé entre-temps."],
"Vragen?":["Questions?","Des questions ?"],
/* bedankt */
"Top, bedankt!":["Great, thank you!","Super, merci !"],
"Ik heb je reactie ontvangen. Ik maak een gratis voorbeeld voor je en hoor snel van me, meestal binnen één werkdag.":["I have received your reply. I will make a free example for you and you will hear from me soon, usually within one working day.","J'ai bien reçu votre réponse. Je vous prépare un exemple gratuit et vous recontacte rapidement, généralement dans un jour ouvrable."],
"Liever meteen even praten?":["Prefer to talk right away?","Vous préférez en parler tout de suite ?"],"Plan een moment":["Book a time","Planifier un moment"],"Bedankt | Marleo":["Thank you | Marleo","Merci | Marleo"],
/* nis2 */
"NIS2 is de Europese richtlijn die de cyberbeveiliging van organisaties versterkt; in België geldt ze via de wet van 26 april 2024. De AI Act regelt het gebruik van kunstmatige intelligentie in Europa. Dit is algemene informatie en geen juridisch advies.":["NIS2 is the European directive that strengthens the cybersecurity of organisations; in Belgium it applies through the law of 26 April 2024. The AI Act regulates the use of artificial intelligence in Europe. This is general information, not legal advice.","NIS2 est la directive européenne qui renforce la cybersécurité des organisations ; en Belgique, elle s'applique via la loi du 26 avril 2024. L'AI Act encadre l'utilisation de l'intelligence artificielle en Europe. Il s'agit d'informations générales, pas d'un avis juridique."],
"NIS2: wat betekent het voor jouw organisatie?":["NIS2: what does it mean for your organisation?","NIS2 : qu'est-ce que cela signifie pour votre organisation ?"],
"Middelgrote en grote organisaties in bepaalde sectoren moeten passende beveiligingsmaatregelen nemen en incidenten melden.":["Medium-sized and large organisations in certain sectors must take appropriate security measures and report incidents.","Les moyennes et grandes organisations de certains secteurs doivent prendre des mesures de sécurité adéquates et signaler les incidents."],
"Ook kleinere bedrijven krijgen ermee te maken als ze leverancier zijn van een organisatie die onder NIS2 valt.":["Smaller companies are also affected if they supply an organisation that falls under NIS2.","Les petites entreprises sont aussi concernées si elles sont fournisseurs d'une organisation soumise à NIS2."],
"Het Centrum voor Cybersecurity België (CCB) is de bevoegde autoriteit:":["The Centre for Cybersecurity Belgium (CCB) is the competent authority:","Le Centre pour la Cybersécurité Belgique (CCB) est l'autorité compétente :"],
"Waar Marleo bij helpt":["How Marleo helps","Comment Marleo vous aide"],
"Een eerste doorlichting van je huidige situatie: back-ups, e-mailbeveiliging (SPF, DKIM, DMARC), toegangsbeheer en updates.":["An initial review of your current situation: backups, email security (SPF, DKIM, DMARC), access management and updates.","Un premier audit de votre situation : sauvegardes, sécurité e-mail (SPF, DKIM, DMARC), gestion des accès et mises à jour."],
"Een praktisch stappenplan met prioriteiten.":["A practical roadmap with priorities.","Un plan d'action pratique avec des priorités."],"Opvolging en beheer van je IT-omgeving.":["Follow-up and management of your IT environment.","Suivi et gestion de votre environnement IT."],
"AI Act":["AI Act","AI Act"],
"Gebruik je AI-tools in je bedrijf? Dan is het verstandig om te weten welke gegevens erin terechtkomen, wie ze gebruikt en welke afspraken er zijn. We helpen je met een verstandig en veilig gebruik.":["Do you use AI tools in your business? Then it is wise to know what data goes into them, who uses them and what agreements apply. We help you use them sensibly and safely.","Vous utilisez des outils d'IA dans votre entreprise ? Il est alors judicieux de savoir quelles données y entrent, qui les utilise et quelles règles s'appliquent. Nous vous aidons à les utiliser de manière sensée et sûre."],
"Plan gerust een vrijblijvend gesprek via":["Feel free to book a no-obligation call via","N'hésitez pas à planifier un entretien sans engagement via"],"of mail naar":["or email","ou écrivez à"],
"NIS2 & AI Act · Marleo":["NIS2 & AI Act · Marleo","NIS2 & AI Act · Marleo"],
/* privacy */
"Privacyverklaring":["Privacy statement","Déclaration de confidentialité"],"Privacyverklaring · Marleo":["Privacy statement · Marleo","Déclaration de confidentialité · Marleo"],
"Marleo respecteert je privacy. Op deze pagina lees je welke persoonsgegevens we verwerken, waarom, hoe lang we ze bewaren en welke rechten je hebt.":["Marleo respects your privacy. On this page you can read which personal data we process, why, how long we keep it and what rights you have.","Marleo respecte votre vie privée. Sur cette page, vous découvrez quelles données personnelles nous traitons, pourquoi, combien de temps nous les conservons et quels sont vos droits."],
"1. Wie is verantwoordelijk?":["1. Who is responsible?","1. Qui est responsable ?"],
"2. Welke gegevens verwerken we?":["2. What data do we process?","2. Quelles données traitons-nous ?"],
"Contactformulier en aanvragen:":["Contact form and requests:","Formulaire de contact et demandes :"],"naam, bedrijf, e-mailadres, telefoonnummer en je bericht.":["name, company, email address, phone number and your message.","nom, entreprise, adresse e-mail, numéro de téléphone et votre message."],
"Afspraken boeken:":["Booking meetings:","Prise de rendez-vous :"],"naam, bedrijf, e-mailadres, telefoonnummer, gekozen datum en tijd, en je eventuele bericht.":["name, company, email address, phone number, chosen date and time, and any message.","nom, entreprise, adresse e-mail, numéro de téléphone, date et heure choisies, et votre éventuel message."],
"Klanten:":["Customers:","Clients :"],"gegevens die nodig zijn voor offertes, facturatie en de uitvoering van onze diensten (bv. facturatiegegevens, domein- en hostinggegevens).":["data needed for quotes, invoicing and delivering our services (e.g. billing details, domain and hosting details).","les données nécessaires aux devis, à la facturation et à l'exécution de nos services (ex. données de facturation, de domaine et d'hébergement)."],
"Communicatie:":["Communication:","Communication :"],"e-mails, berichten en gespreksnotities met ons.":["emails, messages and call notes with us.","e-mails, messages et notes d'entretien avec nous."],
"3. Waarom en op welke grond?":["3. Why and on what basis?","3. Pourquoi et sur quelle base ?"],
"Je vraag beantwoorden of een afspraak plannen: uitvoering van maatregelen op jouw verzoek, en ons gerechtvaardigd belang.":["Answering your question or scheduling a meeting: steps taken at your request, and our legitimate interest.","Répondre à votre question ou planifier un rendez-vous : mesures prises à votre demande et notre intérêt légitime."],
"Een overeenkomst uitvoeren en factureren: uitvoering van de overeenkomst en wettelijke boekhoudverplichtingen.":["Performing an agreement and invoicing: performance of the contract and legal accounting obligations.","Exécuter un contrat et facturer : exécution du contrat et obligations comptables légales."],
"Je informeren over onze diensten: gerechtvaardigd belang of, waar vereist, je toestemming. Je kan je altijd afmelden.":["Informing you about our services: legitimate interest or, where required, your consent. You can always unsubscribe.","Vous informer sur nos services : intérêt légitime ou, si requis, votre consentement. Vous pouvez toujours vous désinscrire."],
"4. Met wie delen we gegevens?":["4. Who do we share data with?","4. Avec qui partageons-nous les données ?"],
"Alleen met dienstverleners die we nodig hebben om te werken, en met wie we afspraken hebben over gegevensbescherming: onder meer Google (e-mail, agenda en Google Meet), Supabase (beveiligde opslag van onze klantenadministratie) en GitHub (hosting van deze website). We verkopen je gegevens nooit.":["Only with service providers we need to operate, with whom we have data protection agreements: including Google (email, calendar and Google Meet), Supabase (secure storage of our customer records) and GitHub (hosting of this website). We never sell your data.","Uniquement avec les prestataires dont nous avons besoin pour travailler et avec qui nous avons des accords de protection des données : notamment Google (e-mail, agenda et Google Meet), Supabase (stockage sécurisé de notre gestion clients) et GitHub (hébergement de ce site). Nous ne vendons jamais vos données."],
"5. Cookies en externe bronnen":["5. Cookies and external resources","5. Cookies et ressources externes"],"Deze website gebruikt":["This website uses","Ce site utilise"],"geen tracking- of advertentiecookies":["no tracking or advertising cookies","aucun cookie de suivi ou publicitaire"],
". Voor het lettertype laden we bestanden van Google Fonts, waarbij je IP-adres aan Google wordt doorgegeven. Wanneer je een afspraak boekt of het contactformulier gebruikt, worden je gegevens verstuurd naar onze beveiligde opslag.":[". For the font we load files from Google Fonts, which passes your IP address to Google. When you book a meeting or use the contact form, your data is sent to our secure storage.",". Pour la police, nous chargeons des fichiers de Google Fonts, ce qui transmet votre adresse IP à Google. Lorsque vous prenez rendez-vous ou utilisez le formulaire de contact, vos données sont envoyées vers notre stockage sécurisé."],
"6. Hoe lang bewaren we gegevens?":["6. How long do we keep data?","6. Combien de temps conservons-nous les données ?"],
"Aanvragen en afspraken die niet tot een opdracht leiden: maximaal 2 jaar.":["Requests and meetings that do not lead to an assignment: up to 2 years.","Demandes et rendez-vous sans suite : 2 ans maximum."],
"Facturen en boekhoudkundige stukken: 7 jaar, zoals wettelijk verplicht.":["Invoices and accounting records: 7 years, as required by law.","Factures et pièces comptables : 7 ans, comme l'exige la loi."],
"Klantgegevens: zolang de samenwerking loopt, en daarna niet langer dan nodig.":["Customer data: as long as we work together, and no longer than necessary afterwards.","Données clients : pendant la collaboration, puis pas plus longtemps que nécessaire."],
"7. Jouw rechten":["7. Your rights","7. Vos droits"],
"Je hebt recht op inzage, verbetering, verwijdering, beperking en overdraagbaarheid van je gegevens, en je kan bezwaar maken tegen verwerking. Stuur je vraag naar":["You have the right to access, rectify, erase, restrict and port your data, and you can object to processing. Send your request to","Vous avez un droit d'accès, de rectification, d'effacement, de limitation et de portabilité de vos données, et vous pouvez vous opposer au traitement. Envoyez votre demande à"],
"; we antwoorden binnen 30 dagen.":["; we reply within 30 days.","; nous répondons dans les 30 jours."],
"Ben je niet tevreden? Dan kan je een klacht indienen bij de Gegevensbeschermingsautoriteit, Drukpersstraat 35, 1000 Brussel (":["Not satisfied? You can file a complaint with the Data Protection Authority, Rue de la Presse 35, 1000 Brussels (","Pas satisfait ? Vous pouvez introduire une plainte auprès de l'Autorité de protection des données, Rue de la Presse 35, 1000 Bruxelles ("],
"8. Beveiliging":["8. Security","8. Sécurité"],
"We beveiligen gegevens met toegangscontrole, versleutelde verbindingen en, voor gevoelige gegevens zoals wachtwoorden, versleutelde opslag. Toegangsgegevens van klanten blijven bij voorkeur bij de klant zelf.":["We protect data with access control, encrypted connections and, for sensitive data such as passwords, encrypted storage. Customer login details preferably remain with the customer.","Nous protégeons les données par un contrôle d'accès, des connexions chiffrées et, pour les données sensibles comme les mots de passe, un stockage chiffré. Les identifiants des clients restent de préférence chez le client."],
"9. Wijzigingen":["9. Changes","9. Modifications"],
"We kunnen deze verklaring aanpassen. De datum bovenaan geeft aan wanneer ze het laatst is bijgewerkt.":["We may update this statement. The date at the top shows when it was last updated.","Nous pouvons modifier cette déclaration. La date en haut indique sa dernière mise à jour."],
/* voorwaarden */
"Algemene voorwaarden · Marleo":["Terms and conditions · Marleo","Conditions générales · Marleo"],
"Deze algemene voorwaarden zijn van toepassing op alle offertes, overeenkomsten en leveringen van Marleo aan klanten. Door een offerte te aanvaarden ga je hiermee akkoord.":["These terms and conditions apply to all quotes, agreements and deliveries by Marleo to customers. By accepting a quote you agree to them.","Les présentes conditions générales s'appliquent à tous les devis, contrats et livraisons de Marleo à ses clients. En acceptant un devis, vous les acceptez."],
"1. Identiteit":["1. Identity","1. Identité"],"2. Offertes en overeenkomst":["2. Quotes and agreement","2. Devis et contrat"],
"Offertes zijn 30 dagen geldig, tenzij anders vermeld. De overeenkomst komt tot stand na schriftelijke of elektronische aanvaarding van de offerte, bijvoorbeeld via de digitale ondertekening. Prijzen zijn uitgedrukt in euro en, tenzij anders vermeld, exclusief btw.":["Quotes are valid for 30 days unless stated otherwise. The agreement is formed after written or electronic acceptance of the quote, for example via the digital signature. Prices are in euro and, unless stated otherwise, exclude VAT.","Les devis sont valables 30 jours, sauf mention contraire. Le contrat est conclu après acceptation écrite ou électronique du devis, par exemple via la signature numérique. Les prix sont exprimés en euros et, sauf mention contraire, hors TVA."],
"3. Uitvoering en medewerking":["3. Execution and cooperation","3. Exécution et collaboration"],
"Marleo voert de opdracht uit naar best vermogen. Levertermijnen zijn indicatief. De klant bezorgt tijdig de nodige teksten, beelden, logo's en toegangen. Vertraging door ontbrekende informatie verlengt de termijn.":["Marleo carries out the assignment to the best of its ability. Delivery times are indicative. The customer provides the necessary texts, images, logos and access in good time. Delays due to missing information extend the deadline.","Marleo exécute la mission au mieux de ses capacités. Les délais sont indicatifs. Le client fournit à temps les textes, images, logos et accès nécessaires. Tout retard dû à des informations manquantes prolonge le délai."],
"4. Demo, feedback en oplevering":["4. Demo, feedback and delivery","4. Démo, retours et livraison"],
"Bij websites tonen we vooraf een demo. De offerte omvat een redelijk aantal aanpassingsrondes; bijkomend werk wordt op voorhand besproken en apart aangerekend. De klant keurt de oplevering goed of meldt binnen 7 dagen schriftelijk zijn opmerkingen.":["For websites we show a demo first. The quote includes a reasonable number of revision rounds; additional work is discussed in advance and charged separately. The customer approves the delivery or reports comments in writing within 7 days.","Pour les sites web, nous montrons d'abord une démo. Le devis comprend un nombre raisonnable de révisions ; tout travail supplémentaire est discuté au préalable et facturé séparément. Le client approuve la livraison ou communique ses remarques par écrit dans les 7 jours."],
"5. Prijs en betaling":["5. Price and payment","5. Prix et paiement"],
"Facturen zijn betaalbaar binnen 14 dagen na factuurdatum, tenzij anders overeengekomen. Marleo kan een voorschot vragen voor de start. Bij te late betaling is van rechtswege en zonder ingebrekestelling een verwijlinterest van 8% per jaar verschuldigd, samen met een forfaitaire schadevergoeding van 10% op het openstaande bedrag (minimum 40 euro). Marleo mag de dienstverlening opschorten zolang facturen onbetaald zijn.":["Invoices are payable within 14 days of the invoice date, unless agreed otherwise. Marleo may request a deposit before starting. In case of late payment, interest of 8% per year is due automatically and without notice, together with a fixed compensation of 10% of the outstanding amount (minimum 40 euro). Marleo may suspend services while invoices remain unpaid.","Les factures sont payables dans les 14 jours suivant leur date, sauf accord contraire. Marleo peut demander un acompte avant le début. En cas de retard de paiement, un intérêt de 8 % par an est dû de plein droit et sans mise en demeure, ainsi qu'une indemnité forfaitaire de 10 % du montant impayé (minimum 40 euros). Marleo peut suspendre ses services tant que des factures restent impayées."],
"6. Eigendom en intellectuele rechten":["6. Ownership and intellectual property","6. Propriété et droits intellectuels"],
"Na volledige betaling verkrijgt de klant het gebruiksrecht op de opgeleverde website of software. Marleo behoudt de rechten op eigen code-bibliotheken, ontwerpprincipes en herbruikbare onderdelen. De klant garandeert dat aangeleverde teksten, beelden en logo's vrij van rechten van derden zijn.":["After full payment the customer obtains the right to use the delivered website or software. Marleo retains the rights to its own code libraries, design principles and reusable components. The customer guarantees that supplied texts, images and logos are free of third-party rights.","Après paiement complet, le client obtient le droit d'utilisation du site ou du logiciel livré. Marleo conserve les droits sur ses propres bibliothèques de code, principes de conception et composants réutilisables. Le client garantit que les textes, images et logos fournis sont libres de droits de tiers."],
"7. Domeinnaam, hosting en toegangen":["7. Domain name, hosting and access","7. Nom de domaine, hébergement et accès"],
"Domeinnamen, hostingaccounts en online profielen blijven bij voorkeur op naam van de klant. Waar Marleo beheer of toegang heeft, gebeurt dat in opdracht van de klant. Jaarlijkse kosten van domein, hosting en licenties worden apart vermeld.":["Domain names, hosting accounts and online profiles preferably remain in the customer's name. Where Marleo has management or access, this is on the customer's behalf. Annual costs for domain, hosting and licences are stated separately.","Les noms de domaine, comptes d'hébergement et profils en ligne restent de préférence au nom du client. Lorsque Marleo en assure la gestion ou y a accès, c'est pour le compte du client. Les frais annuels de domaine, d'hébergement et de licences sont mentionnés séparément."],
"8. Onderhoud en support":["8. Maintenance and support","8. Maintenance et support"],
"Kleine aanpassingen na oplevering, zoals teksten, foto's, openingsuren of prijzen, doen we gratis en zonder abonnement. Grotere uitbreidingen of nieuwe onderdelen bespreken we vooraf en rekenen we apart aan. Hosting en licenties maken alleen deel uit van de overeenkomst als ze in de offerte staan.":["Small changes after delivery, such as texts, photos, opening hours or prices, are free of charge and require no subscription. Larger extensions or new features are discussed in advance and charged separately. Hosting and licences are only part of the agreement if they are included in the quote.","Les petites modifications après livraison, comme les textes, photos, horaires ou prix, sont gratuites et sans abonnement. Les extensions plus importantes ou les nouvelles fonctionnalités sont discutées au préalable et facturées séparément. L'hébergement et les licences ne font partie du contrat que s'ils figurent dans le devis."],
"9. Aansprakelijkheid":["9. Liability","9. Responsabilité"],
"Marleo heeft een middelenverbintenis. Onze aansprakelijkheid is beperkt tot het bedrag dat de klant voor de betrokken opdracht heeft betaald, en dekt geen indirecte schade zoals gederfde winst, verlies van data of omzet. Deze beperking geldt niet bij opzet of zware fout, of wanneer de wet dat verbiedt.":["Marleo has an obligation of means. Our liability is limited to the amount the customer paid for the assignment concerned and does not cover indirect damage such as lost profit, loss of data or revenue. This limitation does not apply in case of intent or gross negligence, or where prohibited by law.","Marleo est tenu d'une obligation de moyens. Notre responsabilité est limitée au montant payé par le client pour la mission concernée et ne couvre pas les dommages indirects tels que la perte de bénéfices, de données ou de chiffre d'affaires. Cette limitation ne s'applique pas en cas de dol ou de faute grave, ou lorsque la loi l'interdit."],
"10. Overmacht":["10. Force majeure","10. Force majeure"],
"Bij overmacht, zoals storingen bij derden, internetuitval of ziekte, is Marleo niet in gebreke voor vertragingen die daaruit voortvloeien.":["In case of force majeure, such as third-party outages, internet failures or illness, Marleo is not in default for resulting delays.","En cas de force majeure, comme des pannes chez des tiers, une coupure internet ou une maladie, Marleo n'est pas en défaut pour les retards qui en découlent."],
"11. Vertrouwelijkheid en privacy":["11. Confidentiality and privacy","11. Confidentialité et vie privée"],
"Beide partijen behandelen vertrouwelijke informatie zorgvuldig. Persoonsgegevens verwerken we volgens onze":["Both parties handle confidential information with care. We process personal data in accordance with our","Les deux parties traitent les informations confidentielles avec soin. Nous traitons les données personnelles conformément à notre"],
"privacyverklaring":["privacy statement","déclaration de confidentialité"],
". Waar we in opdracht van de klant persoonsgegevens verwerken, sluiten we op vraag een verwerkersovereenkomst.":[". Where we process personal data on behalf of the customer, we conclude a data processing agreement on request.",". Lorsque nous traitons des données personnelles pour le compte du client, nous concluons sur demande un contrat de sous-traitance."],
"12. Opzegging":["12. Termination","12. Résiliation"],
"Doorlopende diensten (onderhoud, hosting) kunnen door beide partijen worden opgezegd met een opzegtermijn van 1 maand voor het einde van de lopende periode, tenzij de offerte iets anders bepaalt.":["Ongoing services (maintenance, hosting) can be terminated by either party with 1 month's notice before the end of the current period, unless the quote states otherwise.","Les services continus (maintenance, hébergement) peuvent être résiliés par chaque partie moyennant un préavis d'1 mois avant la fin de la période en cours, sauf disposition contraire du devis."],
"13. Toepasselijk recht en geschillen":["13. Applicable law and disputes","13. Droit applicable et litiges"],
"Belgisch recht is van toepassing. Bij een geschil zoeken we eerst een minnelijke oplossing. Bij gebrek daaraan zijn de rechtbanken van het arrondissement Oost-Vlaanderen bevoegd.":["Belgian law applies. In case of a dispute we first seek an amicable solution. Failing that, the courts of the district of East Flanders have jurisdiction.","Le droit belge s'applique. En cas de litige, nous recherchons d'abord une solution à l'amiable. À défaut, les tribunaux de l'arrondissement de Flandre-Orientale sont compétents."],
"14. Consumenten":["14. Consumers","14. Consommateurs"],
"Deze voorwaarden richten zich tot professionele klanten. Voor consumenten gelden de dwingende wettelijke bepalingen, die steeds voorrang hebben.":["These terms are aimed at professional customers. For consumers, the mandatory legal provisions apply and always take precedence.","Ces conditions s'adressent aux clients professionnels. Pour les consommateurs, les dispositions légales impératives s'appliquent et priment toujours."]
};
var DAYS={en:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],fr:['dimanche','lundi','mardi','mercredi','jeudi','vendredi','samedi'],nl:['zondag','maandag','dinsdag','woensdag','donderdag','vrijdag','zaterdag']};
var DS={en:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],fr:['dim','lun','mar','mer','jeu','ven','sam'],nl:['zo','ma','di','wo','do','vr','za']};
var MONTHS={en:['January','February','March','April','May','June','July','August','September','October','November','December'],fr:['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'],nl:['januari','februari','maart','april','mei','juni','juli','augustus','september','oktober','november','december']};
var MS={en:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],fr:['janv','févr','mars','avr','mai','juin','juil','août','sept','oct','nov','déc'],nl:['jan','feb','mrt','apr','mei','jun','jul','aug','sep','okt','nov','dec']};
window.MT=function(s){if(lang==='nl')return s;var e=D[String(s).trim()];return e?e[lang==='en'?0:1]:s};
window.MDATE={days:DAYS[lang],ds:DS[lang],months:MONTHS[lang],ms:MS[lang]};
function apply(root){if(lang==='nl')return;var w=document.createTreeWalker(root||document.body,NodeFilter.SHOW_TEXT),n,list=[];while(n=w.nextNode())list.push(n);
 list.forEach(function(n){var t=n.nodeValue,k=t.trim();if(!k||!D[k])return;n.nodeValue=t.replace(k,D[k][lang==='en'?0:1])});
 (root||document).querySelectorAll('[placeholder],[aria-label],[title]').forEach(function(e){['placeholder','aria-label','title'].forEach(function(a){var v=e.getAttribute(a);if(v&&D[v])e.setAttribute(a,D[v][lang==='en'?0:1])})});
 if(D[document.title])document.title=D[document.title][lang==='en'?0:1];}
window.MAPPLY=apply;
function links(){document.querySelectorAll('a[href]').forEach(function(a){var h=a.getAttribute('href');if(/^(\.\.\/|\/)(afspraak|privacy|voorwaarden|nis2|bedankt)\/?$/.test(h)||/^\/(afspraak|privacy|voorwaarden|nis2)\/?$/.test(h))a.setAttribute('href',h.replace(/\/?$/,'/')+'?lang='+lang);if(h==='../'||h==='/'||h==='https://marleo.tech'||h==='https://marleo.tech/')a.setAttribute('href',h+'?lang='+lang)})}
function switcher(){var d=document.createElement('div');d.className='mlang';d.innerHTML=L.map(function(l){return '<a href="?lang='+l+'" class="'+(l===lang?'on':'')+'" hreflang="'+l+'">'+l.toUpperCase()+'</a>'}).join('');
 var st=document.createElement('style');st.textContent='.mlang{position:fixed;top:14px;right:14px;z-index:50;display:flex;gap:2px;background:rgba(18,13,18,.85);border:1px solid #3a2b38;border-radius:999px;padding:3px;font:700 12px/1 system-ui,sans-serif}.mlang a{color:#cfc9d2;text-decoration:none;padding:6px 9px;border-radius:999px}.mlang a.on{background:linear-gradient(90deg,#ff8a2b,#ff2a86);color:#fff}';
 document.head.appendChild(st);document.body.appendChild(d)}
function run(){apply();links();switcher()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();
