# Teksten voor de website-audit (NL/EN/FR)
CHK = {
 'ttfb': (('Reactiesnelheid server', 'De server antwoordt traag. Betere hosting of caching (CDN) maakt je site meteen sneller.'),
          ('Server response time', 'The server responds slowly. Better hosting or caching (CDN) makes your site faster right away.'),
          ('Temps de réponse du serveur', 'Le serveur répond lentement. Un meilleur hébergement ou un cache (CDN) accélère immédiatement votre site.')),
 'size': (('Grootte van de pagina', 'De HTML is zwaar. Minder ingebouwde code en scripts laat de pagina sneller laden, zeker op gsm.'),
          ('Page weight', 'The HTML is heavy. Less inline code and fewer scripts make the page load faster, especially on mobile.'),
          ('Poids de la page', 'Le HTML est lourd. Moins de code intégré et de scripts accélère le chargement, surtout sur mobile.')),
 'compress': (('Compressie', 'Bestanden worden niet gecomprimeerd. Gzip of Brotli aanzetten halveert vaak de laadtijd.'),
              ('Compression', 'Files are not compressed. Enabling Gzip or Brotli often halves the load time.'),
              ('Compression', 'Les fichiers ne sont pas compressés. Activer Gzip ou Brotli divise souvent le temps de chargement par deux.')),
 'scripts': (('Aantal scripts', 'Veel externe scripts vertragen je site en kunnen privacyproblemen geven.'),
             ('Number of scripts', 'Many external scripts slow down your site and can cause privacy issues.'),
             ('Nombre de scripts', 'De nombreux scripts externes ralentissent le site et peuvent poser des problèmes de confidentialité.')),
 'lazy': (('Afbeeldingen slim laden', 'Afbeeldingen laden allemaal tegelijk. Met lazy loading verschijnt de pagina sneller.'),
          ('Lazy-loaded images', 'All images load at once. Lazy loading makes the page appear faster.'),
          ('Chargement différé des images', 'Toutes les images se chargent en même temps. Le chargement différé affiche la page plus vite.')),
 'cache': (('Caching', 'Bezoekers moeten alles telkens opnieuw downloaden. Goede cache-instellingen versnellen elk volgend bezoek.'),
           ('Caching', 'Visitors re-download everything every time. Proper cache settings speed up every next visit.'),
           ('Mise en cache', 'Les visiteurs retéléchargent tout à chaque fois. Un bon cache accélère chaque visite suivante.')),
 'title': (('Paginatitel', 'De titel in Google is te kort, te lang of ontbreekt. Ideaal: 15 à 65 tekens met je dienst en regio.'),
           ('Page title', 'The title shown in Google is too short, too long or missing. Ideal: 15–65 characters with your service and region.'),
           ('Titre de la page', 'Le titre affiché dans Google est trop court, trop long ou absent. Idéal : 15 à 65 caractères avec votre service et votre région.')),
 'desc': (('Meta-omschrijving', 'De tekst onder je titel in Google ontbreekt of heeft een slechte lengte (ideaal 50–170 tekens). Een goede omschrijving zorgt voor meer klikken.'),
          ('Meta description', 'The text under your title in Google is missing or poorly sized (ideal 50–170 characters). A good description earns more clicks.'),
          ('Méta-description', 'Le texte sous votre titre dans Google est absent ou mal dimensionné (idéal 50–170 caractères). Une bonne description attire plus de clics.')),
 'h1': (('Hoofdtitel (H1)', 'Elke pagina hoort precies één hoofdtitel te hebben. Zo begrijpt Google waar de pagina over gaat.'),
        ('Main heading (H1)', 'Every page should have exactly one main heading so Google understands what it is about.'),
        ('Titre principal (H1)', 'Chaque page doit avoir exactement un titre principal pour que Google comprenne son sujet.')),
 'lang': (('Taal ingesteld', 'De taal van de pagina is niet ingesteld. Dat helpt Google en schermlezers.'),
          ('Language set', 'The page language is not set. This helps Google and screen readers.'),
          ('Langue définie', 'La langue de la page n’est pas définie. Cela aide Google et les lecteurs d’écran.')),
 'canonical': (('Canonieke link', 'Zonder canonieke link kan Google dubbele versies van je pagina zien.'),
               ('Canonical link', 'Without a canonical link Google may see duplicate versions of your page.'),
               ('Lien canonique', 'Sans lien canonique, Google peut voir des versions en double de votre page.')),
 'og': (('Deelafbeelding (social)', 'Er is geen afbeelding ingesteld voor als iemand je site deelt op WhatsApp, Facebook of LinkedIn.'),
        ('Share image (social)', 'No image is set for when someone shares your site on WhatsApp, Facebook or LinkedIn.'),
        ('Image de partage', 'Aucune image n’est définie lorsque quelqu’un partage votre site sur WhatsApp, Facebook ou LinkedIn.')),
 'schema': (('Gestructureerde gegevens', 'Google krijgt geen gestructureerde info over je bedrijf (adres, openingsuren, reviews). Dat kost zichtbaarheid in de zoekresultaten.'),
            ('Structured data', 'Google gets no structured info about your business (address, hours, reviews), which costs visibility in search results.'),
            ('Données structurées', 'Google ne reçoit aucune info structurée sur votre entreprise (adresse, horaires, avis), ce qui réduit votre visibilité.')),
 'sitemap': (('Sitemap', 'Er is geen sitemap.xml gevonden. Daarmee vindt Google al je pagina’s sneller.'),
             ('Sitemap', 'No sitemap.xml found. A sitemap helps Google find all your pages faster.'),
             ('Plan du site', 'Aucun sitemap.xml trouvé. Il aide Google à trouver toutes vos pages plus vite.')),
 'robots': (('robots.txt', 'Er is geen robots.txt. Niet kritiek, maar wel standaard bij een professionele site.'),
            ('robots.txt', 'No robots.txt found. Not critical, but standard for a professional site.'),
            ('robots.txt', 'Aucun robots.txt trouvé. Pas critique, mais standard pour un site professionnel.')),
 'noindex': (('Zichtbaar in Google', 'Deze pagina vraagt Google om ze NIET te tonen (noindex). Dan word je niet gevonden.'),
             ('Visible in Google', 'This page asks Google NOT to show it (noindex). You won’t be found.'),
             ('Visible dans Google', 'Cette page demande à Google de NE PAS l’afficher (noindex). Vous ne serez pas trouvé.')),
 'alt': (('Beschrijving bij afbeeldingen', 'Afbeeldingen zonder alt-tekst zijn onzichtbaar voor Google Afbeeldingen en schermlezers.'),
         ('Image descriptions', 'Images without alt text are invisible to Google Images and screen readers.'),
         ('Descriptions des images', 'Les images sans texte alternatif sont invisibles pour Google Images et les lecteurs d’écran.')),
 'https': (('Beveiligde verbinding (HTTPS)', 'De site draait niet op HTTPS. Browsers tonen dan "niet veilig" en Google rangschikt je lager.'),
           ('Secure connection (HTTPS)', 'The site is not served over HTTPS. Browsers show “not secure” and Google ranks you lower.'),
           ('Connexion sécurisée (HTTPS)', 'Le site n’est pas servi en HTTPS. Les navigateurs affichent « non sécurisé » et Google vous classe plus bas.')),
 'redirect': (('Doorsturen naar HTTPS', 'Wie http:// intypt, komt niet automatisch op de beveiligde versie terecht.'),
              ('Redirect to HTTPS', 'Visitors typing http:// are not automatically sent to the secure version.'),
              ('Redirection vers HTTPS', 'Les visiteurs qui tapent http:// ne sont pas redirigés automatiquement vers la version sécurisée.')),
 'hsts': (('HSTS', 'De browser wordt niet verplicht om altijd veilig te verbinden. Een extra beveiligingslaag die ontbreekt.'),
          ('HSTS', 'Browsers aren’t forced to always connect securely. An extra security layer is missing.'),
          ('HSTS', 'Le navigateur n’est pas obligé de toujours se connecter en sécurité. Une couche de sécurité manque.')),
 'nosniff': (('Bescherming tegen bestandsmisbruik', 'De header X-Content-Type-Options ontbreekt.'),
             ('Content-type protection', 'The X-Content-Type-Options header is missing.'),
             ('Protection du type de contenu', 'L’en-tête X-Content-Type-Options est absent.')),
 'frame': (('Bescherming tegen clickjacking', 'Je site kan in een frame op een andere site getoond worden (clickjacking).'),
           ('Clickjacking protection', 'Your site can be embedded in a frame on another site (clickjacking).'),
           ('Protection contre le clickjacking', 'Votre site peut être intégré dans un cadre sur un autre site (clickjacking).')),
 'csp': (('Content Security Policy', 'Er is geen beveiligingsbeleid voor scripts. Dat beschermt tegen geïnjecteerde code.'),
         ('Content Security Policy', 'No security policy for scripts. It protects against injected code.'),
         ('Content Security Policy', 'Aucune politique de sécurité des scripts. Elle protège contre le code injecté.')),
 'mixed': (('Gemengde inhoud', 'Sommige onderdelen laden nog via onbeveiligd http://. Dat geeft waarschuwingen in de browser.'),
           ('Mixed content', 'Some resources still load over insecure http://, which triggers browser warnings.'),
           ('Contenu mixte', 'Certaines ressources se chargent encore en http:// non sécurisé, ce qui déclenche des avertissements.')),
 'server': (('Software verborgen', 'De server toont welke softwareversie hij draait. Dat helpt aanvallers gericht zoeken.'),
            ('Software hidden', 'The server reveals which software version it runs, which helps attackers.'),
            ('Logiciel masqué', 'Le serveur révèle sa version logicielle, ce qui aide les attaquants.')),
 'viewport': (('Gsm-vriendelijk', 'De site is niet ingesteld voor gsm’s. Meer dan de helft van je bezoekers zit op een gsm.'),
              ('Mobile-friendly', 'The site is not set up for phones, where most visitors browse.'),
              ('Adapté au mobile', 'Le site n’est pas configuré pour les smartphones, où navigue la majorité des visiteurs.')),
 'icon': (('Favicon', 'Er is geen icoontje voor in het browsertabblad.'),
          ('Favicon', 'There is no icon for the browser tab.'),
          ('Favicon', 'Aucune icône pour l’onglet du navigateur.')),
 'apple': (('Icoon op beginscherm', 'Geen icoon voor wie je site op zijn beginscherm zet (iPhone).'),
           ('Home-screen icon', 'No icon for people who add your site to their home screen (iPhone).'),
           ('Icône d’écran d’accueil', 'Aucune icône pour ceux qui ajoutent votre site à leur écran d’accueil (iPhone).')),
 'tel': (('Bellen met één tik', 'Er is geen klikbaar telefoonnummer. Op gsm wil je dat klanten je meteen kunnen bellen.'),
         ('Tap to call', 'No clickable phone number. On mobile, customers want to call you in one tap.'),
         ('Appel en un clic', 'Aucun numéro cliquable. Sur mobile, les clients veulent vous appeler en un geste.')),
 'theme': (('Themakleur', 'Geen themakleur ingesteld voor de adresbalk op gsm. Klein detail, wel professioneler.'),
           ('Theme colour', 'No theme colour for the mobile address bar. A small detail that looks more professional.'),
           ('Couleur de thème', 'Aucune couleur de thème pour la barre d’adresse mobile. Un détail plus professionnel.')),
}
P = {
 'nl': dict(crumb='Website-audit', title='Gratis website-audit', lead='Laat je website in 15 seconden doorlichten op snelheid, vindbaarheid in Google, beveiliging en gebruik op gsm. Je krijgt meteen een rapport met concrete verbeterpunten.',
    ph='jouwbedrijf.be', btn='Start de audit', busy='Bezig met analyseren…', steps=['Verbinden met de server','Snelheid meten','Beveiliging controleren','SEO en gsm nakijken','Rapport opstellen'],
    cats={'perf':'Snelheid','seo':'Vindbaarheid (SEO)','sec':'Beveiliging','mob':'Gsm & gebruik'}, total='Totaalscore', good='In orde', warn='Kan beter', bad='Aandachtspunt',
    issues='Verbeterpunten', passed='Wat al goed zit', none='Geen verbeterpunten gevonden in deze categorie.',
    ctaT='Wil je dit laten oplossen?', ctaB='We bespreken het rapport samen en geven je een concreet voorstel, zonder verplichtingen.', ctaBtn='Plan een gesprek', ctaMail='Stuur me het rapport',
    mailT='Ontvang het rapport met persoonlijk advies', mailName='Naam', mailEmail='E-mailadres', mailSend='Verstuur', mailOk='Bedankt! We sturen je het rapport en ons advies binnen 1 werkdag.',
    errUrl='Vul een geldig webadres in, bijvoorbeeld jouwbedrijf.be.', errReach='We konden deze website niet bereiken. Klopt het adres?', errLimit='Je hebt de limiet bereikt. Probeer het later opnieuw.',
    note='De audit is een automatische technische controle van de startpagina. Voor een volledige analyse van alle pagina’s, inhoud en conversie plannen we graag een gesprek.',
    how='Wat we controleren', howItems=[('Snelheid','Reactietijd van de server, paginagewicht, compressie, caching en het aantal scripts.'),('Vindbaarheid','Titel, omschrijving, koppen, sitemap, gestructureerde gegevens en zichtbaarheid in Google.'),('Beveiliging','HTTPS, doorverwijzing, beveiligingsheaders, gemengde inhoud en zichtbare softwareversies.'),('Gsm & gebruik','Gsm-weergave, iconen, klikbare telefoonnummers en afwerking.')],
    metaT='Gratis website-audit · Marleo', metaD='Laat je website gratis doorlichten op snelheid, SEO, beveiliging en gsm-gebruik. Direct een rapport met concrete verbeterpunten.', teaser='Scoort jouw website goed? Doe de gratis audit', teaserCta='Start de audit'),
 'en': dict(crumb='Website audit', title='Free website audit', lead='Get your website checked in 15 seconds for speed, Google visibility, security and mobile use. You instantly receive a report with concrete improvements.',
    ph='yourcompany.com', btn='Run the audit', busy='Analysing…', steps=['Connecting to the server','Measuring speed','Checking security','Reviewing SEO and mobile','Building your report'],
    cats={'perf':'Speed','seo':'Visibility (SEO)','sec':'Security','mob':'Mobile & usability'}, total='Overall score', good='Good', warn='Could be better', bad='Needs attention',
    issues='Improvements', passed='What’s already good', none='No improvements found in this category.',
    ctaT='Want this fixed?', ctaB='We walk through the report together and give you a concrete proposal, with no obligation.', ctaBtn='Book a call', ctaMail='Email me the report',
    mailT='Receive the report with personal advice', mailName='Name', mailEmail='Email address', mailSend='Send', mailOk='Thank you! We’ll send the report and our advice within 1 working day.',
    errUrl='Enter a valid web address, e.g. yourcompany.com.', errReach='We couldn’t reach this website. Is the address correct?', errLimit='You’ve reached the limit. Please try again later.',
    note='The audit is an automated technical check of the homepage. For a full analysis of all pages, content and conversion, we’re happy to plan a call.',
    how='What we check', howItems=[('Speed','Server response, page weight, compression, caching and scripts.'),('Visibility','Title, description, headings, sitemap, structured data and Google visibility.'),('Security','HTTPS, redirects, security headers, mixed content and exposed software versions.'),('Mobile & usability','Mobile rendering, icons, tap-to-call and finishing touches.')],
    metaT='Free website audit · Marleo', metaD='Get a free check of your website’s speed, SEO, security and mobile use, with an instant report of concrete improvements.', teaser='Is your website up to standard? Take the free audit', teaserCta='Run the audit'),
 'fr': dict(crumb='Audit de site', title='Audit de site gratuit', lead='Faites analyser votre site en 15 secondes : vitesse, visibilité sur Google, sécurité et usage mobile. Vous recevez immédiatement un rapport avec des points d’amélioration concrets.',
    ph='votreentreprise.be', btn='Lancer l’audit', busy='Analyse en cours…', steps=['Connexion au serveur','Mesure de la vitesse','Contrôle de la sécurité','Vérification SEO et mobile','Rédaction du rapport'],
    cats={'perf':'Vitesse','seo':'Visibilité (SEO)','sec':'Sécurité','mob':'Mobile & usage'}, total='Score global', good='Correct', warn='Peut mieux faire', bad='À corriger',
    issues='Points d’amélioration', passed='Ce qui est déjà bon', none='Aucun point d’amélioration dans cette catégorie.',
    ctaT='Vous voulez que nous corrigions cela ?', ctaB='Nous parcourons le rapport ensemble et vous faisons une proposition concrète, sans engagement.', ctaBtn='Planifier un appel', ctaMail='Recevoir le rapport',
    mailT='Recevez le rapport avec des conseils personnalisés', mailName='Nom', mailEmail='Adresse e-mail', mailSend='Envoyer', mailOk='Merci ! Nous vous envoyons le rapport et nos conseils sous 1 jour ouvrable.',
    errUrl='Entrez une adresse web valide, par ex. votreentreprise.be.', errReach='Nous n’avons pas pu joindre ce site. L’adresse est-elle correcte ?', errLimit='Vous avez atteint la limite. Réessayez plus tard.',
    note='L’audit est un contrôle technique automatique de la page d’accueil. Pour une analyse complète de toutes les pages, du contenu et de la conversion, planifions un appel.',
    how='Ce que nous contrôlons', howItems=[('Vitesse','Réponse du serveur, poids de la page, compression, cache et scripts.'),('Visibilité','Titre, description, titres, sitemap, données structurées et visibilité Google.'),('Sécurité','HTTPS, redirections, en-têtes de sécurité, contenu mixte et versions logicielles exposées.'),('Mobile & usage','Affichage mobile, icônes, appel en un clic et finitions.')],
    metaT='Audit de site gratuit · Marleo', metaD='Analyse gratuite de la vitesse, du SEO, de la sécurité et de l’usage mobile de votre site, avec un rapport immédiat.', teaser='Votre site est-il à niveau ? Faites l’audit gratuit', teaserCta='Lancer l’audit'),
}
