# Case-studypagina's: functies per project (enkel wat echt gebouwd is) + vertalingen
F = {
 'prices': ('Overzichtelijke prijzen per dienst', 'Clear pricing per service', 'Tarifs clairs par service'),
 'beforeafter': ('Interactieve voor/na-vergelijkers', 'Interactive before/after sliders', 'Comparateurs avant/après interactifs'),
 'quote': ('Offerteaanvraag via een formulier', 'Quote request form', 'Formulaire de demande de devis'),
 'services': ('Duidelijk overzicht van alle diensten', 'Clear overview of all services', 'Aperçu clair de tous les services'),
 'gallery': ('Galerij met eigen werk', 'Gallery of their own work', 'Galerie de réalisations'),
 'booking': ('Online afspraken maken', 'Online appointment booking', 'Prise de rendez-vous en ligne'),
 'portfolio': ('Portfolio met realisaties', 'Portfolio of completed projects', 'Portfolio de réalisations'),
 'architects': ('Aparte pagina voor architecten', 'Dedicated page for architects', 'Page dédiée aux architectes'),
 'domains': ('Uitleg per vakgebied: KNX, verlichting, klimaat, energie, netwerk en beveiliging', 'Expertise pages: KNX, lighting, climate, energy, network and security', 'Pages par expertise : KNX, éclairage, climat, énergie, réseau et sécurité'),
 'vision': ('Visie en aanbod helder uitgelegd', 'Vision and offering clearly explained', 'Vision et offre clairement expliquées'),
 'reviews': ('Reviews van klanten', 'Customer reviews', 'Avis clients'),
 'courses': ('Overzicht van opleidingen', 'Overview of training courses', 'Aperçu des formations'),
 'tow': ('Aparte pagina voor trekhaakmontage', 'Dedicated tow-bar fitting page', 'Page dédiée au montage d’attelage'),
 'calc3d': ('Live 3D-prijscalculator: klanten zien meteen een prijs', 'Live 3D price calculator with instant quotes', 'Calculateur de prix 3D en direct'),
 'tables': ('Online tafelreservaties', 'Online table reservations', 'Réservation de tables en ligne'),
 'dashboard': ('Beheerdashboard voor de zaakvoerder', 'Management dashboard for the owner', 'Tableau de bord de gestion pour le gérant'),
 'multilang': ('Meertalig', 'Multilingual', 'Multilingue'),
 'menu': ('Online menukaart', 'Online menu', 'Carte en ligne'),
 'takeaway': ('Take-away', 'Take-away', 'Plats à emporter'),
 'logo': ('Logo en huisstijl', 'Logo and brand identity', 'Logo et identité visuelle'),
 'print': ('Flyers en drukwerk', 'Flyers and print', 'Flyers et imprimés'),
 'regions': ('Pagina’s per werkgebied', 'Pages per service area', 'Pages par zone d’intervention'),
 'whatsapp': ('Contact via WhatsApp met één tik', 'One-tap WhatsApp contact', 'Contact WhatsApp en un geste'),
 'nfc': ('Productpagina’s voor NFC-reviewkaarten en -plaquettes', 'Product pages for NFC review cards and plaques', 'Pages produits pour cartes et plaques d’avis NFC'),
 'card': ('Visitekaartje', 'Business card', 'Carte de visite'),
 'realisations': ('Realisaties in beeld', 'Completed projects showcased', 'Réalisations mises en valeur'),
 'onsite': ('Service op locatie en in de werkplaats', 'On-site and in-workshop service', 'Service sur place et en atelier'),
 'mobile': ('Volledig afgestemd op gsm en tablet', 'Fully optimised for phone and tablet', 'Entièrement optimisé pour mobile et tablette'),
 'seo': ('Basis voor vindbaarheid in Google', 'Foundations for Google visibility', 'Bases pour la visibilité sur Google'),
 'ssl': ('Beveiligde verbinding (SSL) en snelle hosting', 'Secure connection (SSL) and fast hosting', 'Connexion sécurisée (SSL) et hébergement rapide'),
}
C = {
 'foam': ['prices', 'beforeafter', 'quote', 'onsite'],
 'abdo': ['services', 'prices', 'gallery', 'booking'],
 'jema': ['domains', 'portfolio', 'architects', 'quote'],
 'lieven': ['services', 'realisations', 'quote'],
 'nemet': ['vision', 'services', 'reviews', 'courses'],
 'monga': ['services', 'prices', 'tow', 'quote'],
 'elena': ['services', 'prices', 'booking'],
 'tcc': ['calc3d', 'services', 'quote'],
 'paindumie': ['tables', 'dashboard', 'menu'],
 'nava': ['multilang', 'menu', 'tables', 'takeaway'],
 'terraclean': ['services', 'quote', 'logo', 'print'],
 'rani': ['services', 'regions', 'whatsapp'],
 'trusttap': ['nfc', 'card', 'logo'],
}
T = {
 'nl': dict(case='Case', built='Wat we opleverden', scope='Onze rol', scopeV=['Strategie en structuur', 'Webdesign', 'Ontwikkeling', 'Hosting en onderhoud'], client='Klant', sector='Sector', loc='Regio', site='Website', live='Bekijk de live website', more='Meer projecten', prev='Vorig project', next='Volgend project', view='Bekijk de case',
           intro='Voor %s ontwierpen en bouwden we een website op maat die past bij de zaak en bezoekers vlot naar contact of een aanvraag leidt.'),
 'en': dict(case='Case', built='What we delivered', scope='Our role', scopeV=['Strategy and structure', 'Web design', 'Development', 'Hosting and maintenance'], client='Client', sector='Sector', loc='Region', site='Website', live='Visit the live website', more='More projects', prev='Previous project', next='Next project', view='View the case',
           intro='For %s we designed and built a custom website that fits the business and guides visitors smoothly towards contact or a request.'),
 'fr': dict(case='Étude de cas', built='Ce que nous avons livré', scope='Notre rôle', scopeV=['Stratégie et structure', 'Webdesign', 'Développement', 'Hébergement et maintenance'], client='Client', sector='Secteur', loc='Région', site='Site web', live='Voir le site en ligne', more='Plus de projets', prev='Projet précédent', next='Projet suivant', view='Voir l’étude de cas',
           intro='Pour %s, nous avons conçu et développé un site sur mesure, adapté à l’entreprise, qui guide les visiteurs vers un contact ou une demande.'),
}
