# -*- coding: utf-8 -*-
"""Extra content for the static marleo.tech build: deep-dive per service, portfolio, UI strings."""

UI = {
 'nl': dict(
  langName='Nederlands', menu='Menu', close='Sluiten', skip='Naar inhoud',
  forWho='Voor wie', included='Wat er allemaal in zit', outcomes='Wat je ervan merkt',
  related='Past hier ook bij', next='Volgende stap', nextBody='Een gesprek van 30 minuten: we bekijken wat er al is en wat je echt nodig hebt.',
  book='Plan een afspraak', allWork='Alle websites die we bouwden', allWorkLead='Elke site hieronder staat live en is door ons ontworpen en gebouwd. Klik door en bekijk ze zelf, op je gsm of op je computer.',
  visit='Bekijk live', work='Werk', workCta='Bekijk al ons werk', homeWorkTitle='Recent werk', homeWorkLead='Websites die we ontwierpen en bouwden voor ondernemers in heel Vlaanderen.',
  servicesCta='Alle diensten', explore='Ontdek', faq='Veelgestelde vragen', home='Home',
  sent='Bedankt! We nemen snel contact op.', sending='Versturen…', err='Er ging iets mis, probeer opnieuw of mail info@marleo.tech.',
  waOpt='Stuur me ook een bevestiging via WhatsApp', required='Vul je naam en e-mail of telefoon in.',
  footerMade='Ontworpen en gebouwd in Nevele.', scrollTop='Naar boven',
  metaHome='Marleo — managed IT, cloud, security, AI-infrastructuur en websites op maat. Eén partner voor je volledige digitale omgeving, vanuit Nevele (België).',
 ),
 'en': dict(
  langName='English', menu='Menu', close='Close', skip='Skip to content',
  forWho='Who it is for', included="What's included", outcomes='What you notice',
  related='Goes well with', next='Next step', nextBody='A 30-minute call: we look at what is already there and what you really need.',
  book='Book a meeting', allWork='Every website we built', allWorkLead='Every site below is live and was designed and built by us. Click through and see for yourself, on your phone or your computer.',
  visit='View live', work='Work', workCta='See all our work', homeWorkTitle='Recent work', homeWorkLead='Websites we designed and built for business owners across Flanders.',
  servicesCta='All services', explore='Explore', faq='Frequently asked questions', home='Home',
  sent='Thank you! We will be in touch shortly.', sending='Sending…', err='Something went wrong, please try again or email info@marleo.tech.',
  waOpt='Also send me a confirmation on WhatsApp', required='Please enter your name and email or phone.',
  footerMade='Designed and built in Nevele, Belgium.', scrollTop='Back to top',
  metaHome='Marleo — managed IT, cloud, security, AI infrastructure and custom websites. One partner for your entire digital environment, based in Belgium.',
 ),
 'fr': dict(
  langName='Français', menu='Menu', close='Fermer', skip='Aller au contenu',
  forWho='Pour qui', included='Ce qui est inclus', outcomes='Ce que vous remarquez',
  related='Va bien avec', next='Prochaine étape', nextBody="Un échange de 30 minutes : nous regardons ce qui existe déjà et ce dont vous avez vraiment besoin.",
  book='Prendre rendez-vous', allWork='Tous les sites que nous avons créés', allWorkLead="Chaque site ci-dessous est en ligne et a été conçu et développé par nous. Cliquez et voyez par vous-même, sur mobile ou sur ordinateur.",
  visit='Voir le site', work='Réalisations', workCta='Voir toutes nos réalisations', homeWorkTitle='Réalisations récentes', homeWorkLead='Des sites conçus et développés pour des entrepreneurs dans toute la Flandre.',
  servicesCta='Tous les services', explore='Découvrir', faq='Questions fréquentes', home='Accueil',
  sent='Merci ! Nous vous contactons rapidement.', sending='Envoi…', err='Une erreur est survenue, réessayez ou écrivez à info@marleo.tech.',
  waOpt='Envoyez-moi aussi une confirmation sur WhatsApp', required='Indiquez votre nom et votre e-mail ou téléphone.',
  footerMade='Conçu et développé à Nevele, Belgique.', scrollTop='Haut de page',
  metaHome="Marleo — IT managé, cloud, sécurité, infrastructure IA et sites web sur mesure. Un seul partenaire pour tout votre environnement numérique, depuis la Belgique.",
 ),
}

# ---------------------------------------------------------------------------
# Deep dive per service: forWho (3), included (8), outcomes (3 x title/body), related keys
DEEP = {
 'managed-it': {
  'related': ['security', 'cloud', 'prijzen'],
  'nl': dict(forWho=['Kmo\'s en organisaties van 10 tot 500 medewerkers zonder eigen IT-afdeling', 'Bedrijven die hun huidige IT-partner te traag of te onduidelijk vinden', 'IT-verantwoordelijken die werk willen uitbesteden maar de controle willen houden'],
   included=['Inventaris van alle toestellen, licenties en garanties', 'Automatische updates voor Windows, macOS en software', 'Monitoring van back-ups, schijven en certificaten', 'Servicedesk via telefoon, mail en ticketportaal', 'Onboarding en offboarding van medewerkers', 'Beheer van netwerk, wifi en firewall', 'Maandrapport in gewone taal', 'Kwartaaloverleg met roadmap en budget'],
   outcomes=[('Minder onderbrekingen', 'Problemen worden vaak opgelost voordat je medewerkers ze merken.'), ('Eén aanspreekpunt', 'Geen doorverwijzen tussen leveranciers: wij nemen het op en volgen op.'), ('Voorspelbare kosten', 'Een vaste prijs per werkplek, vooraf begroot.')]),
  'en': dict(forWho=['SMEs and organisations of 10 to 500 staff without an in-house IT team', 'Companies that find their current IT partner too slow or unclear', 'IT leads who want to outsource the work but keep control'],
   included=['Inventory of all devices, licences and warranties', 'Automatic updates for Windows, macOS and software', 'Monitoring of backups, disks and certificates', 'Service desk by phone, email and ticket portal', 'On- and offboarding of employees', 'Network, Wi-Fi and firewall management', 'Monthly report in plain language', 'Quarterly review with roadmap and budget'],
   outcomes=[('Fewer interruptions', 'Issues are often solved before your staff notice them.'), ('One point of contact', 'No bouncing between suppliers: we pick up and follow through.'), ('Predictable costs', 'A fixed price per workstation, budgeted upfront.')]),
  'fr': dict(forWho=["PME et organisations de 10 à 500 collaborateurs sans service IT interne", "Entreprises qui trouvent leur partenaire IT actuel trop lent ou peu clair", "Responsables IT qui veulent externaliser sans perdre le contrôle"],
   included=["Inventaire de tous les appareils, licences et garanties", "Mises à jour automatiques Windows, macOS et logiciels", "Surveillance des sauvegardes, disques et certificats", "Service desk par téléphone, e-mail et portail de tickets", "Arrivées et départs des collaborateurs", "Gestion du réseau, du wifi et du pare-feu", "Rapport mensuel en langage clair", "Revue trimestrielle avec feuille de route et budget"],
   outcomes=[("Moins d'interruptions", "Les problèmes sont souvent réglés avant que vos équipes ne les remarquent."), ("Un seul interlocuteur", "Pas de renvoi entre fournisseurs : nous prenons en charge et assurons le suivi."), ("Des coûts prévisibles", "Un prix fixe par poste, budgété à l'avance.")]),
 },
 'cloud': {
  'related': ['managed-it', 'security', 'ai-infrastructuur'],
  'nl': dict(forWho=['Bedrijven die nog met losse mailboxen of een oude server werken', 'Teams die vanop elke plek veilig willen samenwerken', 'Organisaties die Microsoft 365 hebben maar er maar half gebruik van maken'],
   included=['Migratie van mail, agenda\'s en bestanden zonder dataverlies', 'Inrichting van Teams, SharePoint en OneDrive', 'Tweestapsverificatie voor elke gebruiker', 'Gedeelde mappen en rechten per afdeling', 'Back-up van Microsoft 365-data', 'Azure-omgevingen voor servers en toepassingen', 'Kostenbewaking op licenties en cloudverbruik', 'Opleiding voor je team, kort en praktisch'],
   outcomes=[('Overal toegang', 'Je bestanden en mail veilig op elk toestel, ook onderweg.'), ('Minder licentiekosten', 'We ruimen ongebruikte licenties op en kiezen het juiste pakket.'), ('Geen oude server meer', 'Minder hardware, minder storingen, minder zorgen.')]),
  'en': dict(forWho=['Companies still running separate mailboxes or an old server', 'Teams that want to collaborate safely from anywhere', 'Organisations that have Microsoft 365 but only use half of it'],
   included=['Migration of mail, calendars and files without data loss', 'Setup of Teams, SharePoint and OneDrive', 'Two-factor authentication for every user', 'Shared folders and permissions per department', 'Backup of Microsoft 365 data', 'Azure environments for servers and applications', 'Cost monitoring on licences and cloud usage', 'Short, practical training for your team'],
   outcomes=[('Access from anywhere', 'Your files and mail safely available on every device.'), ('Lower licence costs', 'We clean up unused licences and pick the right plan.'), ('No more old server', 'Less hardware, fewer outages, fewer worries.')]),
  'fr': dict(forWho=["Entreprises qui utilisent encore des boîtes mail séparées ou un vieux serveur", "Équipes qui veulent collaborer en sécurité depuis n'importe où", "Organisations qui ont Microsoft 365 mais n'en utilisent que la moitié"],
   included=["Migration des e-mails, agendas et fichiers sans perte de données", "Mise en place de Teams, SharePoint et OneDrive", "Double authentification pour chaque utilisateur", "Dossiers partagés et droits par service", "Sauvegarde des données Microsoft 365", "Environnements Azure pour serveurs et applications", "Suivi des coûts de licences et du cloud", "Formation courte et pratique pour votre équipe"],
   outcomes=[("Accès partout", "Vos fichiers et e-mails en sécurité sur chaque appareil."), ("Moins de frais de licences", "Nous supprimons les licences inutilisées et choisissons la bonne offre."), ("Plus de vieux serveur", "Moins de matériel, moins de pannes, moins de soucis.")]),
 },
 'security': {
  'related': ['managed-it', 'cloud', 'ai-infrastructuur'],
  'nl': dict(forWho=['Bedrijven die onder NIS2 vallen of leveren aan bedrijven die dat doen', 'Organisaties die al eens phishing of een gehackte mailbox hadden', 'Directies die willen weten hoe veilig ze écht zijn'],
   included=['Tweestapsverificatie (MFA) voor alle accounts', 'Endpoint-detectie op elke laptop en server', 'Mailbeveiliging: SPF, DKIM en DMARC correct ingesteld', 'Back-ups volgens de 3-2-1-regel, met hersteltest', 'Phishing-simulatie en korte bewustmaking voor je team', 'Overzicht van wie waar toegang toe heeft', 'Incidentplan: wie doet wat als het misgaat', 'Documentatie richting NIS2 en verzekeraar'],
   outcomes=[('Kleinere kans op een lek', 'De meeste aanvallen stoppen bij MFA en goede mailbeveiliging.'), ('Sneller herstel', 'Geteste back-ups betekenen uren in plaats van dagen.'), ('Een dossier dat klopt', 'Klaar voor audits, klanten en je cyberverzekering.')]),
  'en': dict(forWho=['Companies covered by NIS2 or supplying to companies that are', 'Organisations that have already faced phishing or a hacked mailbox', 'Management teams that want to know how secure they really are'],
   included=['Multi-factor authentication (MFA) on every account', 'Endpoint detection on every laptop and server', 'Email security: SPF, DKIM and DMARC set up correctly', 'Backups following the 3-2-1 rule, with restore tests', 'Phishing simulation and short awareness training', 'Overview of who has access to what', 'Incident plan: who does what when things go wrong', 'Documentation for NIS2 and your insurer'],
   outcomes=[('Lower chance of a breach', 'Most attacks stop at MFA and proper email security.'), ('Faster recovery', 'Tested backups mean hours instead of days.'), ('A file that holds up', 'Ready for audits, customers and your cyber insurance.')]),
  'fr': dict(forWho=["Entreprises soumises à NIS2 ou fournisseurs de telles entreprises", "Organisations ayant déjà subi du phishing ou une boîte mail piratée", "Directions qui veulent savoir à quel point elles sont vraiment protégées"],
   included=["Double authentification (MFA) sur tous les comptes", "Détection sur chaque portable et serveur", "Sécurité e-mail : SPF, DKIM et DMARC bien configurés", "Sauvegardes selon la règle 3-2-1, avec test de restauration", "Simulation de phishing et courte sensibilisation", "Vue claire de qui a accès à quoi", "Plan d'incident : qui fait quoi en cas de problème", "Documentation pour NIS2 et votre assureur"],
   outcomes=[("Moins de risque de fuite", "La plupart des attaques s'arrêtent au MFA et à une bonne sécurité e-mail."), ("Reprise plus rapide", "Des sauvegardes testées, ce sont des heures au lieu de jours."), ("Un dossier solide", "Prêt pour les audits, les clients et votre cyber-assurance.")]),
 },
 'ai-infrastructuur': {
  'related': ['development', 'cloud', 'security'],
  'nl': dict(forWho=['Bedrijven die AI willen gebruiken zonder hun data naar buiten te sturen', 'Teams die nu al met losse AI-tools werken en daar grip op willen', 'Organisaties met veel documenten, procedures of klantvragen'],
   included=['Readiness scan: waar zit waarde, wat mag wettelijk', 'Keuze en hosting van het model, on-premise of in Azure', 'Koppeling met je eigen documenten en systemen (RAG)', 'Toegangsrechten per gebruiker en afdeling', 'Logging en audittrail van elke vraag en elk antwoord', 'Kostenbewaking per gebruiker en toepassing', 'Training voor je medewerkers', 'Dossier richting de EU AI Act'],
   outcomes=[('Antwoorden uit je eigen kennis', 'Medewerkers vinden procedures en info in seconden.'), ('Data blijft binnen', 'Niets gaat zonder jouw akkoord naar externe diensten.'), ('Grip op kosten en risico', 'Je ziet wie wat gebruikt en wat het kost.')]),
  'en': dict(forWho=['Companies that want to use AI without sending their data outside', 'Teams already using separate AI tools who want control over them', 'Organisations with lots of documents, procedures or customer questions'],
   included=['Readiness scan: where the value is, what is legally allowed', 'Model choice and hosting, on-premise or in Azure', 'Connection to your own documents and systems (RAG)', 'Access rights per user and department', 'Logging and audit trail of every question and answer', 'Cost monitoring per user and application', 'Training for your staff', 'Documentation for the EU AI Act'],
   outcomes=[('Answers from your own knowledge', 'Staff find procedures and information in seconds.'), ('Data stays inside', 'Nothing goes to external services without your approval.'), ('Control over cost and risk', 'You see who uses what and what it costs.')]),
  'fr': dict(forWho=["Entreprises qui veulent utiliser l'IA sans envoyer leurs données à l'extérieur", "Équipes qui utilisent déjà des outils IA dispersés et veulent les maîtriser", "Organisations avec beaucoup de documents, procédures ou questions clients"],
   included=["Scan de maturité : où est la valeur, ce qui est permis légalement", "Choix et hébergement du modèle, sur site ou dans Azure", "Connexion à vos propres documents et systèmes (RAG)", "Droits d'accès par utilisateur et service", "Journalisation et piste d'audit de chaque question et réponse", "Suivi des coûts par utilisateur et application", "Formation de vos collaborateurs", "Dossier pour l'AI Act européen"],
   outcomes=[("Des réponses issues de votre savoir", "Vos équipes trouvent procédures et infos en quelques secondes."), ("Les données restent chez vous", "Rien ne part vers des services externes sans votre accord."), ("Maîtrise des coûts et des risques", "Vous voyez qui utilise quoi et combien cela coûte.")]),
 },
 'development': {
  'related': ['ai-infrastructuur', 'webshop', 'websites'],
  'nl': dict(forWho=['Bedrijven die werken met Excel-lijsten die te groot zijn geworden', 'Teams die dezelfde gegevens in drie systemen intypen', 'Ondernemers die een eigen klantenportaal of CRM willen'],
   included=['Analyse van je huidige werkwijze en knelpunten', 'Ontwerp van schermen, eerst op papier, dan klikbaar', 'Maatwerk-CRM, planning, offertes en facturen', 'Koppelingen met boekhouding, webshop, mail en agenda', 'Automatische taken, herinneringen en rapporten', 'Werkt op computer én gsm', 'Veilige cloud-opslag met dagelijkse back-up', 'Documentatie en overdracht: de code is van jou'],
   outcomes=[('Minder dubbel werk', 'Gegevens één keer invoeren, overal beschikbaar.'), ('Overzicht', 'Eén plek waar je ziet wat openstaat en wat er moet gebeuren.'), ('Groeit met je mee', 'Nieuwe functies erbij wanneer je ze nodig hebt.')]),
  'en': dict(forWho=['Companies running on spreadsheets that have outgrown themselves', 'Teams typing the same data into three systems', 'Business owners who want their own customer portal or CRM'],
   included=['Analysis of your current workflow and bottlenecks', 'Screen design, first on paper, then clickable', 'Custom CRM, planning, quotes and invoices', 'Integrations with accounting, webshop, mail and calendar', 'Automatic tasks, reminders and reports', 'Works on desktop and mobile', 'Secure cloud storage with daily backups', 'Documentation and handover: the code is yours'],
   outcomes=[('Less double work', 'Enter data once, available everywhere.'), ('Overview', 'One place to see what is open and what needs doing.'), ('Grows with you', 'New features added when you need them.')]),
  'fr': dict(forWho=["Entreprises qui travaillent avec des fichiers Excel devenus trop gros", "Équipes qui saisissent les mêmes données dans trois systèmes", "Entrepreneurs qui veulent leur propre portail client ou CRM"],
   included=["Analyse de votre façon de travailler et des points de blocage", "Conception des écrans, d'abord sur papier, puis cliquables", "CRM, planning, devis et factures sur mesure", "Connexions avec la comptabilité, la boutique, l'e-mail et l'agenda", "Tâches, rappels et rapports automatiques", "Fonctionne sur ordinateur et mobile", "Stockage cloud sécurisé avec sauvegarde quotidienne", "Documentation et transfert : le code vous appartient"],
   outcomes=[("Moins de double travail", "Saisir une fois, disponible partout."), ("Une vue d'ensemble", "Un seul endroit pour voir ce qui est ouvert et ce qu'il reste à faire."), ("Grandit avec vous", "De nouvelles fonctions quand vous en avez besoin.")]),
 },
 'webshop': {
  'related': ['websites', 'branding', 'development'],
  'nl': dict(forWho=['Winkels en makers die online willen verkopen', 'Bedrijven die bestellingen nu per mail of telefoon krijgen', 'Webshops die traag zijn of slecht werken op de gsm'],
   included=['Productcatalogus met varianten, foto\'s en voorraad', 'Online betalen met Bancontact, kaart en Payconiq', 'Bestelmails en verzendopvolging', 'Kortingscodes en acties', 'Koppeling met boekhouding of facturatie', 'Algemene voorwaarden en privacy in orde', 'Snel en overzichtelijk op de gsm', 'Opleiding zodat je zelf producten beheert'],
   outcomes=[('Verkopen terwijl je slaapt', 'Bestellingen komen binnen, ook buiten de openingsuren.'), ('Minder handwerk', 'Betaling, bevestiging en factuur lopen automatisch.'), ('Vertrouwen bij klanten', 'Een professionele shop die veilig aanvoelt.')]),
  'en': dict(forWho=['Shops and makers who want to sell online', 'Companies that currently take orders by email or phone', 'Webshops that are slow or work badly on mobile'],
   included=['Product catalogue with variants, photos and stock', 'Online payment with Bancontact, card and Payconiq', 'Order emails and shipping updates', 'Discount codes and promotions', 'Link with accounting or invoicing', 'Terms and privacy in order', 'Fast and clear on mobile', 'Training so you manage products yourself'],
   outcomes=[('Sell while you sleep', 'Orders come in, also outside opening hours.'), ('Less manual work', 'Payment, confirmation and invoice run automatically.'), ('Customer trust', 'A professional shop that feels safe.')]),
  'fr': dict(forWho=["Commerces et créateurs qui veulent vendre en ligne", "Entreprises qui reçoivent aujourd'hui leurs commandes par e-mail ou téléphone", "Boutiques en ligne lentes ou peu pratiques sur mobile"],
   included=["Catalogue avec variantes, photos et stock", "Paiement en ligne par Bancontact, carte et Payconiq", "E-mails de commande et suivi d'expédition", "Codes promo et actions", "Liaison avec la comptabilité ou la facturation", "Conditions générales et vie privée en ordre", "Rapide et clair sur mobile", "Formation pour gérer vous-même vos produits"],
   outcomes=[("Vendre pendant que vous dormez", "Les commandes arrivent, même en dehors des heures d'ouverture."), ("Moins de travail manuel", "Paiement, confirmation et facture se font automatiquement."), ("La confiance des clients", "Une boutique professionnelle qui inspire confiance.")]),
 },
 'websites': {
  'related': ['branding', 'webshop', 'domeincheck'],
  'nl': dict(forWho=['Zelfstandigen en kmo\'s zonder (goede) website', 'Bedrijven met een site die traag, verouderd of niet mobielvriendelijk is', 'Ondernemers die willen gevonden worden in hun regio'],
   included=['Ontwerp op maat in jouw huisstijl, geen template', 'Teksten die zeggen wat je doet en waar', 'Perfect op gsm, tablet en computer', 'Contactformulier, WhatsApp-knop en afspraakmodule', 'Technische SEO: titels, snelheid, sitemap, Google', 'Koppeling met je Google-bedrijfsprofiel', 'SSL, hosting en back-ups geregeld', 'Kleine aanpassingen achteraf gratis'],
   outcomes=[('Beter gevonden', 'Een snelle, duidelijke site scoort beter in Google.'), ('Meer aanvragen', 'Bezoekers vinden meteen hoe ze je bereiken.'), ('Professionele eerste indruk', 'Je site ziet eruit zoals je werk: verzorgd.')]),
  'en': dict(forWho=['Freelancers and SMEs without a (good) website', 'Companies with a site that is slow, outdated or not mobile-friendly', 'Business owners who want to be found in their region'],
   included=['Custom design in your brand, no template', 'Copy that says what you do and where', 'Perfect on phone, tablet and computer', 'Contact form, WhatsApp button and booking module', 'Technical SEO: titles, speed, sitemap, Google', 'Link with your Google Business Profile', 'SSL, hosting and backups taken care of', 'Small changes afterwards for free'],
   outcomes=[('Found more often', 'A fast, clear site ranks better in Google.'), ('More enquiries', 'Visitors immediately see how to reach you.'), ('A professional first impression', 'Your site looks like your work: polished.')]),
  'fr': dict(forWho=["Indépendants et PME sans (bon) site web", "Entreprises avec un site lent, dépassé ou pas adapté au mobile", "Entrepreneurs qui veulent être trouvés dans leur région"],
   included=["Design sur mesure à votre image, pas de modèle", "Des textes qui disent ce que vous faites et où", "Parfait sur mobile, tablette et ordinateur", "Formulaire de contact, bouton WhatsApp et prise de rendez-vous", "SEO technique : titres, vitesse, sitemap, Google", "Lien avec votre fiche Google Business", "SSL, hébergement et sauvegardes réglés", "Petites modifications ensuite gratuites"],
   outcomes=[("Mieux trouvé", "Un site rapide et clair se classe mieux sur Google."), ("Plus de demandes", "Les visiteurs voient tout de suite comment vous joindre."), ("Une première impression professionnelle", "Votre site ressemble à votre travail : soigné.")]),
 },
 'games': {
  'related': ['development', 'branding', 'websites'],
  'nl': dict(forWho=['Merken die een campagne speels willen maken', 'Scholen en opleiders die iets willen laten oefenen', 'Evenementen die bezoekers willen laten meedoen'],
   included=['Concept en spelregels samen uitgewerkt', 'Grafische stijl in jouw huisstijl', 'Speelbaar in de browser, zonder installatie', 'Werkt op gsm, tablet en computer', 'Scores, highscores en klassementen', 'Deelknoppen voor sociale media', 'Optioneel: leadformulier of wedstrijd', 'Hosting en statistieken'],
   outcomes=[('Mensen blijven langer', 'Een spel houdt aandacht vast waar een folder dat niet doet.'), ('Gedeeld en besproken', 'Leuke spellen worden doorgestuurd.'), ('Iets wat bijblijft', 'Je merk wordt een ervaring.')]),
  'en': dict(forWho=['Brands that want a playful campaign', 'Schools and trainers who want people to practise', 'Events that want visitors to join in'],
   included=['Concept and game rules worked out together', 'Visual style in your brand', 'Playable in the browser, no install', 'Works on phone, tablet and computer', 'Scores, high scores and leaderboards', 'Share buttons for social media', 'Optional: lead form or contest', 'Hosting and statistics'],
   outcomes=[('People stay longer', 'A game holds attention where a flyer does not.'), ('Shared and talked about', 'Fun games get passed on.'), ('Something memorable', 'Your brand becomes an experience.')]),
  'fr': dict(forWho=["Marques qui veulent une campagne ludique", "Écoles et formateurs qui veulent faire pratiquer", "Événements qui veulent faire participer le public"],
   included=["Concept et règles du jeu élaborés ensemble", "Style graphique à votre image", "Jouable dans le navigateur, sans installation", "Fonctionne sur mobile, tablette et ordinateur", "Scores, meilleurs scores et classements", "Boutons de partage pour les réseaux sociaux", "En option : formulaire de contact ou concours", "Hébergement et statistiques"],
   outcomes=[("On reste plus longtemps", "Un jeu capte l'attention là où un dépliant échoue."), ("Partagé et commenté", "Les jeux amusants circulent."), ("Une expérience qui marque", "Votre marque devient une expérience.")]),
 },
 'branding': {
  'related': ['websites', 'webshop', 'games'],
  'nl': dict(forWho=['Nieuwe zaken die een herkenbaar merk willen', 'Bedrijven met een logo dat niet meer bij hen past', 'Ondernemers die overal een andere stijl gebruiken'],
   included=['Kort gesprek over wie je bent en voor wie je werkt', 'Logo in kleur, zwart-wit en als icoon', 'Kleurenpalet en lettertypes', 'Visitekaartjes, briefpapier en e-mailhandtekening', 'Sjablonen voor sociale media', 'Bestanden voor print én web', 'Een korte stijlgids om alles consequent te houden', 'Optioneel: flyers, belettering en signalisatie'],
   outcomes=[('Herkenbaar', 'Mensen onthouden je sneller.'), ('Consequent', 'Overal dezelfde, verzorgde uitstraling.'), ('Klaar voor groei', 'Een merk dat ook werkt op je website en webshop.')]),
  'en': dict(forWho=['New businesses that want a recognisable brand', 'Companies with a logo that no longer fits', 'Business owners using a different style everywhere'],
   included=['Short talk about who you are and who you serve', 'Logo in colour, black-and-white and as an icon', 'Colour palette and typefaces', 'Business cards, letterhead and email signature', 'Social media templates', 'Files for print and web', 'A short style guide to keep everything consistent', 'Optional: flyers, lettering and signage'],
   outcomes=[('Recognisable', 'People remember you faster.'), ('Consistent', 'The same polished look everywhere.'), ('Ready to grow', 'A brand that also works on your website and shop.')]),
  'fr': dict(forWho=["Nouvelles entreprises qui veulent une marque reconnaissable", "Entreprises dont le logo ne leur correspond plus", "Entrepreneurs qui utilisent un style différent partout"],
   included=["Court échange sur qui vous êtes et pour qui vous travaillez", "Logo en couleur, noir et blanc et en icône", "Palette de couleurs et typographies", "Cartes de visite, papier à en-tête et signature e-mail", "Modèles pour les réseaux sociaux", "Fichiers pour l'impression et le web", "Un petit guide de style pour rester cohérent", "En option : flyers, lettrage et signalétique"],
   outcomes=[("Reconnaissable", "On se souvient de vous plus vite."), ("Cohérent", "Partout la même image soignée."), ("Prêt à grandir", "Une marque qui fonctionne aussi sur votre site et votre boutique.")]),
 },
}

# ---------------------------------------------------------------------------
# Portfolio: every website we built (live). img = key in shots folder (s_<img>_d.png / _m.png)
PORTFOLIO = [
 dict(name='Foamoré Detailing', url='https://foamoredetailing.be', img='foam',
  nl=('Auto detailing · Laarne', 'Premium zwart-goud site met prijzen, voor/na-sliders en offerteaanvraag.'),
  en=('Car detailing · Laarne', 'Premium black & gold site with prices, before/after sliders and quote requests.'),
  fr=('Detailing auto · Laarne', 'Site premium noir et or avec tarifs, comparateurs avant/après et demande de devis.')),
 dict(name='Hair Creations by Abdo', url='https://hcbyabdo.be', img='abdo',
  nl=('Barbershop & kapsalon · Kortrijk', 'Luxe site in de stijl van het HC-logo, met alle diensten, prijzen en galerij.'),
  en=('Barbershop & hair salon · Kortrijk', 'Luxury site in the style of the HC logo, with all services, prices and gallery.'),
  fr=('Barbier & salon de coiffure · Courtrai', 'Site luxueux dans le style du logo HC, avec services, tarifs et galerie.')),
 dict(name='Jematech', url='https://jematech.be', img='jema',
  nl=('Slimme technieken · Knokke, Latem & Antwerpen', 'Premium site voor KNX, verlichting, klimaat en netwerk, met portfolio en pagina voor architecten.'),
  en=('Smart home technology · Knokke, Latem & Antwerp', 'Premium site for KNX, lighting, climate and network, with portfolio and a page for architects.'),
  fr=('Techniques intelligentes · Knokke, Latem & Anvers', 'Site premium pour KNX, éclairage, climat et réseau, avec portfolio et page pour architectes.')),
 dict(name='Tuinen Lieven Cornelis', url='https://tuinenlievencornelis.be', img='lieven',
  nl=('Tuinaannemer · Aalter', 'Frisse site voor tuinontwerp, aanleg en onderhoud, met realisaties en aanvraagformulier.'),
  en=('Garden contractor · Aalter', 'Fresh site for garden design, landscaping and maintenance, with projects and request form.'),
  fr=('Paysagiste · Aalter', 'Site frais pour conception, aménagement et entretien de jardins, avec réalisations et formulaire.')),
 dict(name='Nemetona', url='https://nemetona.be', img='nemet',
  nl=('Holistische praktijk · Aalter', 'Rustige, warme site met visie, aanbod, reviews en opleidingen.'),
  en=('Holistic practice · Aalter', 'Calm, warm site with vision, offering, reviews and trainings.'),
  fr=('Cabinet holistique · Aalter', 'Site calme et chaleureux avec vision, offre, avis et formations.')),
 dict(name='MONGA Automotive', url='https://monga-automotive.netlify.app', img='monga',
  nl=('Bestelwagen inrichting & cardetailing · Eernegem', 'Stoere site met diensten, tarieven, trekhaakmontage en offerteaanvraag.'),
  en=('Van conversions & car detailing · Eernegem', 'Bold site with services, prices, towbar fitting and quote requests.'),
  fr=('Aménagement d’utilitaires & detailing · Eernegem', 'Site percutant avec services, tarifs, montage d’attelage et demande de devis.')),
 dict(name='Beauty Salon Elena', url='https://beautysalonelena.be', img='elena',
  nl=('Kapsalon, nagels, massage & yoga · Kortrijk', 'Elegante site met alle diensten, prijzen en online afspraken.'),
  en=('Hair, nails, massage & yoga · Kortrijk', 'Elegant site with all services, prices and online booking.'),
  fr=('Coiffure, ongles, massage & yoga · Courtrai', 'Site élégant avec services, tarifs et rendez-vous en ligne.')),
 dict(name='The Cleaning Company', url='https://thecleaningcompany-be.com', img='tcc',
  nl=('Zetel- en tapijtreiniging · regio Gent', 'Site met live 3D-prijscalculator: klanten krijgen meteen een prijs.'),
  en=('Sofa & carpet cleaning · Ghent region', 'Site with a live 3D price calculator: customers get a price instantly.'),
  fr=('Nettoyage de canapés & tapis · région de Gand', 'Site avec calculateur de prix 3D en direct : un prix immédiat.')),
 dict(name='Pain du Mie', url='https://paindumie.be', img='paindumie',
  nl=('Bakkerij & tearoom · Bazel', 'Warme site met online tafelreservaties en beheerdashboard.'),
  en=('Bakery & tearoom · Bazel', 'Warm site with online table reservations and admin dashboard.'),
  fr=('Boulangerie & salon de thé · Bazel', 'Site chaleureux avec réservation de table en ligne et tableau de bord.')),
 dict(name='Café Restaurant Nava', url='https://cafenava.be', img='nava',
  nl=('Perzisch café · Gent', 'Meertalige site met menukaart, reservaties en take-away.'),
  en=('Persian café · Ghent', 'Multilingual site with menu, bookings and take-away.'),
  fr=('Café persan · Gand', 'Site multilingue avec carte, réservations et plats à emporter.')),
 dict(name='TerraClean NB', url='https://terracleannb.be', img='terraclean',
  nl=('Buitenreiniging · Deinze', 'Site die aanvragen oplevert, plus logo, flyers en drukwerk.'),
  en=('Outdoor cleaning · Deinze', 'Lead-generating site, plus logo, flyers and print.'),
  fr=('Nettoyage extérieur · Deinze', 'Site qui génère des demandes, plus logo, flyers et imprimés.')),
 dict(name='Rani Poetsservice', url='https://ranipoetsservice.be', img='rani',
  nl=('Poetsdienst · regio Kortrijk', 'Moderne site met diensten, regio\'s en WhatsApp-contact.'),
  en=('Cleaning service · Kortrijk region', 'Modern site with services, areas and WhatsApp contact.'),
  fr=('Service de nettoyage · région de Courtrai', 'Site moderne avec services, zones et contact WhatsApp.')),
 dict(name='TrustTap', url='https://trusttap.be', img='trusttap',
  nl=('NFC-reviewkaarten · webshop', 'Drietalig merk en webshop, met eigen CRM voor bestellingen.'),
  en=('NFC review cards · webshop', 'Trilingual brand and webshop, with a custom CRM for orders.'),
  fr=('Cartes d’avis NFC · boutique', 'Marque et boutique trilingues, avec CRM sur mesure pour les commandes.')),
]
